// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'fr';

export type Locales = 'en' | 'fr';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	pages: {
		/**
		 * A​c​c​u​e​i​l
		 */
		home: string;
	};
	header: {
		/**
		 * A​r​t​i​s​t​e​s
		 */
		artists: string;
		/**
		 * S​n​e​a​k​e​r​s
		 */
		sneakers: string;
		/**
		 * L​e​ ​c​o​n​c​e​p​t
		 */
		concept: string;
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string;
		/**
		 * A​r​t​i​c​l​e​s
		 */
		items: string;
		/**
		 * S​o​u​s​-​t​o​t​a​l
		 */
		subtotal: string;
		/**
		 * V​o​i​r​ ​l​e​ ​p​a​n​i​e​r
		 */
		cart: string;
		/**
		 * R​e​c​h​e​r​c​h​e​r​ ​u​n​ ​p​r​o​d​u​i​t​.​.​.
		 */
		search: string;
		/**
		 * M​o​n​ ​c​o​m​p​t​e
		 */
		account: string;
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		login: string;
		/**
		 * S​e​ ​d​é​c​o​n​n​e​c​t​e​r
		 */
		logout: string;
		/**
		 * S​'​i​n​s​c​r​i​r​e
		 */
		register: string;
		/**
		 * M​e​s​ ​c​o​m​m​a​n​d​e​s
		 */
		orders: string;
		/**
		 * P​a​r​a​m​è​t​r​e​s
		 */
		settings: string;
	};
	footer: {
		/**
		 * L​e​s​ ​a​r​t​i​s​t​e​s
		 */
		artists: string;
		/**
		 * L​e​s​ ​c​o​l​l​e​c​t​i​o​n​s
		 */
		collections: string;
		/**
		 * L​e​ ​c​o​n​c​e​p​t​ ​M​y​S​n​k​r​s
		 */
		concept: string;
		/**
		 * A​v​i​s​ ​c​l​i​e​n​t​s
		 */
		customerReviews: string;
		/**
		 * C​o​n​t​a​c​t​e​z​-​n​o​u​s
		 */
		contactUs: string;
		/**
		 * L​i​e​n​s​ ​u​t​i​l​e​s
		 */
		usefulLinks: string;
		/**
		 * N​o​s​ ​m​a​r​q​u​e​s
		 */
		brands: string;
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​s
		 */
		information: string;
		/**
		 * A​i​d​e
		 */
		help: string;
		/**
		 * M​e​n​t​i​o​n​s​ ​l​é​g​a​l​e​s
		 */
		legal: string;
		/**
		 * C​o​n​d​i​t​i​o​n​s​ ​g​é​n​é​r​a​l​e​s​ ​d​e​ ​v​e​n​t​e
		 */
		terms: string;
		/**
		 * C​o​n​d​i​t​i​o​n​s
		 */
		conditions: string;
		/**
		 * P​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é
		 */
		cookies: string;
		/**
		 * S​t​a​t​u​t​ ​d​e​ ​l​a​ ​c​o​m​m​a​n​d​e
		 */
		orderStatus: string;
		/**
		 * E​x​p​é​d​i​t​i​o​n​ ​e​t​ ​l​i​v​r​a​i​s​o​n
		 */
		shipping: string;
		/**
		 * R​e​t​o​u​r​s
		 */
		returns: string;
		/**
		 * M​o​y​e​n​s​ ​d​e​ ​p​a​i​e​m​e​n​t
		 */
		payment: string;
		/**
		 * T​o​u​s​ ​d​r​o​i​t​s​ ​r​é​s​e​r​v​é​s
		 */
		allRightsReserved: string;
		/**
		 * S​u​i​v​e​z​-​n​o​u​s
		 */
		follow: string;
	};
};

export type TranslationFunctions = {
	pages: {
		/**
		 * Accueil
		 */
		home: () => LocalizedString;
	};
	header: {
		/**
		 * Artistes
		 */
		artists: () => LocalizedString;
		/**
		 * Sneakers
		 */
		sneakers: () => LocalizedString;
		/**
		 * Le concept
		 */
		concept: () => LocalizedString;
		/**
		 * Contact
		 */
		contact: () => LocalizedString;
		/**
		 * Articles
		 */
		items: () => LocalizedString;
		/**
		 * Sous-total
		 */
		subtotal: () => LocalizedString;
		/**
		 * Voir le panier
		 */
		cart: () => LocalizedString;
		/**
		 * Rechercher un produit...
		 */
		search: () => LocalizedString;
		/**
		 * Mon compte
		 */
		account: () => LocalizedString;
		/**
		 * Se connecter
		 */
		login: () => LocalizedString;
		/**
		 * Se déconnecter
		 */
		logout: () => LocalizedString;
		/**
		 * S'inscrire
		 */
		register: () => LocalizedString;
		/**
		 * Mes commandes
		 */
		orders: () => LocalizedString;
		/**
		 * Paramètres
		 */
		settings: () => LocalizedString;
	};
	footer: {
		/**
		 * Les artistes
		 */
		artists: () => LocalizedString;
		/**
		 * Les collections
		 */
		collections: () => LocalizedString;
		/**
		 * Le concept MySnkrs
		 */
		concept: () => LocalizedString;
		/**
		 * Avis clients
		 */
		customerReviews: () => LocalizedString;
		/**
		 * Contactez-nous
		 */
		contactUs: () => LocalizedString;
		/**
		 * Liens utiles
		 */
		usefulLinks: () => LocalizedString;
		/**
		 * Nos marques
		 */
		brands: () => LocalizedString;
		/**
		 * Informations
		 */
		information: () => LocalizedString;
		/**
		 * Aide
		 */
		help: () => LocalizedString;
		/**
		 * Mentions légales
		 */
		legal: () => LocalizedString;
		/**
		 * Conditions générales de vente
		 */
		terms: () => LocalizedString;
		/**
		 * Conditions
		 */
		conditions: () => LocalizedString;
		/**
		 * Politique de confidentialité
		 */
		cookies: () => LocalizedString;
		/**
		 * Statut de la commande
		 */
		orderStatus: () => LocalizedString;
		/**
		 * Expédition et livraison
		 */
		shipping: () => LocalizedString;
		/**
		 * Retours
		 */
		returns: () => LocalizedString;
		/**
		 * Moyens de paiement
		 */
		payment: () => LocalizedString;
		/**
		 * Tous droits réservés
		 */
		allRightsReserved: () => LocalizedString;
		/**
		 * Suivez-nous
		 */
		follow: () => LocalizedString;
	};
};

export type Formatters = {};
